### ISSUE TITLE
Create project creation function

### ISSUE THREAD

**Issue by YJDoc2** [djunicode/ergo#20]
Create a function that will take required parameters such as project name, type of project (Node,python etc.) and will create a folder as well as run appropriate initialization function, such as npm init or cargo init etc. This folder should be created in a centralized space, particular to our app.
Make sure that you test this function, and create mocha tests for making sure that this runs, with proper harness and mocking of required data.

**Comment by raj2729** [comment]
I would like to work on this issue

**Comment by YJDoc2** [comment]
closed by #24 and #27
