### ISSUE TITLE
Create a function to launch shell and run commands

### ISSUE THREAD

**Issue by YJDoc2** [djunicode/ergo#21]
Create a function that will launch respective shell in a separate process , and then run the given command. Make sure that this run in both windows and Linux. Currently let's first implement this for Debian based distros, so that x-terminal-emulator will be mapped to default terminal emulator of the system (check out https://vitux.com/how-to-set-the-gnome-default-terminal-emulator-on-ubuntu/). For windows this should launch cmd/powershell. Make sure to test this on both platform for launching terminal as well as running the command and appropriately write tests for checking terminal has been launched and command is run
Also make sure that only respective tests are run on given platform (Tests for Windows on Windows and tests for Linux on Linux).

**Comment by ADIthaker** [comment]
i want to try this

**Comment by YJDoc2** [comment]
closed by #23
