### ISSUE TITLE
Create funtion to launch file manager and preffered/default code editor

### ISSUE THREAD

**Issue by YJDoc2** [djunicode/ergo#22]
Write a function that will take appropriate parameters and launch the default file manager and code editor in the specified directory.
For Linux, this can be done using xdg-open (check https://itsfoss.com/install-nemo-file-manager-ubuntu/), which will launch file navigator in specified folder. For Windows the function should launch the windows default file manager in given directory.
Write tests to check if file manager and code editors are actually launched or not, also make sure that either the preferred (global or language-specific) or default code editor is launched.
Make sure to test on both platforms, and write mocha tests for both platforms.

**Comment by hridmod** [comment]
i will work on this

**Comment by YJDoc2** [comment]
Closed by #25
