### ISSUE TITLE
Set up logger

### ISSUE THREAD

**Issue by YJDoc2** [djunicode/ergo#3]
Set up a logger to log various information when the application will run/ error occurs.
check out [electron-log](https://www.npmjs.com/package/electron-log) which provides a simple interface for logging, without needing to specify log path.
Make sure the logger is working in both the main.js file for electron and int the render process itself. For working with logger in renderer process, one needs to export the logger in preload.js. Read the docs of the template to understand the security aspects and requirements for preload.

**Comment by raj2729** [comment]
I would like to work on this issue .

**Comment by hridmod** [comment]
i want to work on this issue

**Comment by YJDoc2** [comment]
closed by #13
