### ISSUE TITLE
Set up exporting of backend functions api to renderer process

### ISSUE THREAD

**Issue by YJDoc2** [djunicode/ergo#5]
We will need to export all of the 'backend' functions to the renderer process, so we can call them from the GUI. Create appropriate folders to define the backend functions, and create index.js file to exports all functions. One would need to import this in the preload.js and export in the preload. Make sure to read the docs of template to know the security aspects of preload.js nad requirements.

**Comment by ADIthaker** [comment]
i want to work on this

**Comment by YJDoc2** [comment]
Closed by #16
